---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:623d49fed10413958921ac13436f7a3e69e6cf572f40a22aff0c959cff2b2c03"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
checkmk_server_web_service: "apache2"
...
