---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:98700f34d1314635e2b9e9b4f70f1620dfc2f3cfac2429bd44253d7631aa4917"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
