---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:2cafca4829a49eab670997892d39688ee54579dc5f617906b6292b1bad2814a8"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
