---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:b8a503e4ff317afd81fa3979d1976f08b64cd48fe0c255a93779ac18a2ed7969"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
checkmk_server_web_service: "apache2"
...
