---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:2906a2c16ded4fd07e2389bf9002f6368711b3a3b0cd38efd436a32f0e5b16a7"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
checkmk_server_web_service: "apache2"
...
