---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:109bb23701d2bd2952131cf11dde502e73478bc11e727a0daa80158d8b20f167"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
