---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:00e922c1881f7bd05db8630adbcecb8d4e311b339de0e727353212ab372187f3"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
