---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:986649b721add22ab75f3f8f56c1668cc0024822c15159db67a74f029a7d0242"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
