---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:efd6af7ad0a4a784d061ff534445da719ac49b029930e59f4b25e53592777759"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
