---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:ac0559f8a7d69cff050db3cbacf573293a486d5860ad771b3b26bc7a056dbc11"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
