---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:d35aa30fa825fd90e6423ba588b7e8e1c89827c063ab393596638febc721ca02"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
checkmk_server_web_service: "apache2"
...
