---
# default (Ubuntu 18.04 "Bionic Beaver") variables file for checkmk_server
checkmk_server_download: "check-mk-raw-{{ checkmk_server_version }}_0.{{ ansible_distribution_release }}_amd64.deb"
checkmk_server_download_checksum: "sha256:bc1a195c66b47f29212afd3555330f5e7e0a8e626469645bcf4d8fa9ae8120a2"
checkmk_server_prerequisites:
  - python3-apt
  - python3-passlib
...
