---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "${{ github.repository }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: centos7
          - distro: centos8
          - distro: debian9
          - distro: debian10
          - distro: ubuntu1804
          - distro: ubuntu2004
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install test dependencies
        run: pip install 'ansible${{ matrix.ansible-version }}' molecule[docker] docker
      - name: Run Molecule tests
        run: |
          molecule test
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_VERBOSITY: '2'
          MOLECULE_DEBUG: '1'
          MOLECULE_DISTRO: "${{ matrix.distro }}"
          PY_COLORS: '1'
...
